default:
  image: openjdk:18-alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build

build_job:
  stage: build
  script:
    - ./gradlew build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
